name: CD - Deploy to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Azure Developer CLI
      uses: Azure/setup-azd@v0.1.0
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
    
    - name: Deploy to Production
      run: |
        azd env new healio-prod --location eastus
        azd env set AZURE_OPENAI_SYSTEM_MESSAGE "${{ secrets.PROD_SYSTEM_MESSAGE }}"
        azd env set AUTH_CLIENT_ID "${{ secrets.PROD_AUTH_CLIENT_ID }}"
        azd env set AUTH_CLIENT_SECRET "${{ secrets.PROD_AUTH_CLIENT_SECRET }}"
        azd up --no-prompt
    
    - name: Smoke tests
      run: |
        export BACKEND_URL=$(azd env get-values --output json | jq -r '.BACKEND_URI')
        pytest tests/smoke/ --backend-url=$BACKEND_URL
    
    - name: Update production monitoring
      run: |
        # Update Application Insights alerts
        # Update health checks
        # Enable monitoring dashboards
